### ISSUE TITLE
Add platform icon Homebrew

### ISSUE THREAD

**Issue by bmuenzenmeyer** [bmuenzenmeyer/nodejs.org#36]
Add the Homebrew logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/b38b96cb-b868-424f-b200-2d143751f8fc)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=423-27584&mode=dev)

> displaying all. This issue only adds the homebrew one.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `platform-homebrew.svg`

Paste the below contents into the new file and save.

```
<svg width="32" height="32" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0_429_2384)"><path fill-rule="evenodd" clip-rule="evenodd" d="M14.175 5.943c.087-2.773-.847-4.408-3.533-5.488-.763 2.67 2.388 5.132 3.533 5.488Z" fill="#D1D3D4" stroke="#000" stroke-width=".566" stroke-linejoin="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M21.458 10.643c.088-2.277-.488-3.196-.92-3.853-.437-.614-1.488-1.577-2.78-1.617-1.22-.039-1.514.636-2.64.677-.185-2.051 1.363-3.177 1.363-3.177s-.424-.598-.774-.745c-.504.448-1.89 1.941-1.57 3.863-1.036-.198-1.767-.792-2.856-.578-1.484.292-2.706 1.19-3.403 3.157-.697 1.968.246 4.264.45 4.92.206.656 1.723 3.444 2.912 3.854 1.188.41 1.189.225 1.824-.02.636-.247 1.6-.697 3.014-.185 1.414.512 1.599.635 2.48.061.882-.573 2.03-2.357 2.296-2.87.266-.512.41-.778.492-1.045.857-.427.033-.4.112-2.442Z" fill="#D1D3D4" stroke="#000" stroke-width=".566" stroke-linejoin="round"/><path d="M23.76 27.287a2.128 2.128 0 0 0 2.133-2.125v-7.656a2.126 2.126 0 0 0-2.125-2.126h-1.753a.473.473 0 0 1-.472-.472v-1.113H7.724l.035 16.32a.472.472 0 0 0 .218.397c.616.357 2.589 1.034 6.732 1.034 4.23 0 6.12-.907 6.662-1.316a.471.471 0 0 0 .17-.361c.002-.452.002-1.498.002-2.117a.471.471 0 0 1 .482-.472c.52.007 1.143.008 1.735.007Zm-2.217-9.424a.591.591 0 0 1 .59-.59h1.505a.59.59 0 0 1 .59.59v6.87a.59.59 0 0 1-.59.591h-1.504a.591.591 0 0 1-.59-.59v-6.87Z" fill="#fff" stroke="#000" stroke-width=".566" stroke-linejoin="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M9.086 13.658v14.64c0 .17.09.325.237.41.598.284 2.331.964 5.37.964 3.06 0 4.743-.826 5.306-1.166a.47.47 0 0 0 .216-.396V13.658H9.087Z" fill="#FBB040"/><path d="M10.722 16.137v11.314" stroke="#FFDB96" stroke-width="1.302" stroke-linecap="round"/><path fill-rule="evenodd" clip-rule="evenodd" d="M17.01 16.662a.82.82 0 0 0-.367-.66 1.975 1.975 0 0 1-.82-.98c-3.022.102-5.78-.429-7.17-.803a11.605 11.605 0 0 0-1.082-.252 1.814 1.814 0 0 1-1.464-1.773c0-.967.767-1.752 1.725-1.787a2.189 2.189 0 1 1 4.217 1.117l.006.002a2.095 2.095 0 0 1 3.985-.016 2.277 2.277 0 0 1 4.436-.918l.199-.05a1.789 1.789 0 1 1 1.122 3.33 2.637 2.637 0 0 0-.578.15c-.518.195-1.048.357-1.584.491a1.964 1.964 0 0 1-.225.736 2.447 2.447 0 0 0-.281 1.33v.201c0 .585-.474.941-1.06.941a1.06 1.06 0 0 1-1.059-1.06Z" fill="#fff" stroke="#000" stroke-width=".566" stroke-linecap="round" stroke-linejoin="round"/></g><defs><clipPath id="clip0_429_2384"><path fill="#fff" d="M5.373 0h21.255v32H5.373z"/></clipPath></defs></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add a file called `platform-logos.stories.tsx` to the `components/__design__` directory. If this file already exists, open it instead.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const PlatformLogos: StoryObj = {};

export default {
  title: 'Design System/Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src="/static/images/logos/platform-apple.svg"
            alt="Apple Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-nvm.svg"
            alt="NVM Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-microsoft.svg"
            alt="Microsoft Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-homebrew.svg"
            alt="Homebrew Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/platform-placeholder.svg"
            alt="Placeholder Logo"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--platform-logos and you should see the file you added.

<details><summary>Preview</summary>
<img src="https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/eab605bf-6576-4284-a190-fa4c11196061" />
</details>

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by joycexfang** [comment]
i can take this issue!

**Comment by bmuenzenmeyer** [comment]
done
