### ISSUE TITLE
Add social icon GitHub

### ISSUE THREAD

**Issue by bmuenzenmeyer** [bmuenzenmeyer/nodejs.org#38]
Add the GitHub logo to the site assets. 

> [Read more about the Node.js Website redesign](https://github.com/nodejs/nodejs.org/discussions/5131)

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/a05c6e3f-f0f9-4be0-b8b6-249b47442109)

> from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8379&mode=dev)

> displaying all. This issue only adds the GitHub one. It's white and hard to see.

---

### Before You Start...

- Use the [Contributor's Guide](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md) to learn how to [setup your environment](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#getting-started), run [available commands](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#cli-commands), and construct [proper commits](https://github.com/nodejs/nodejs.org/blob/main/CONTRIBUTING.md#commit-guidelines).
- Review the [technologies used](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#technologies-used-in-the-website) when building the site, and [why they were chosen](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#remarks-on-technologies-used).
- Review the [component creation guide](https://github.com/nodejs/nodejs.org/blob/main/COLLABORATOR_GUIDE.md#creating-components) to follow our standards.

Make sure that `npm ci` completes for you in a terminal pointing to your fork. If it doesn't or you aren't sure, ask a mentor.

---

#### Where to add the file

Site assets are found at https://github.com/nodejs/nodejs.org/tree/main/public/static/images/logos. 

- Add the file into this directory _on your fork_

#### Adding the file

This file is an SVG, which means it is represented as text.

Create a new file in the `public/static/images/logos` directory, called `social-github.svg`

Paste the below contents into the new file and save.

```
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"><path fill="#fff" d="M10 1.25A8.748 8.748 0 0 0 1.25 10a8.744 8.744 0 0 0 5.983 8.302c.437.076.601-.186.601-.416 0-.208-.01-.897-.01-1.63-2.199.405-2.768-.536-2.943-1.028-.098-.251-.525-1.028-.897-1.236-.306-.164-.743-.569-.01-.58.688-.01 1.18.635 1.345.897.787 1.324 2.045.952 2.548.722.077-.569.306-.951.558-1.17-1.947-.219-3.981-.974-3.981-4.32 0-.952.339-1.74.897-2.352-.088-.219-.394-1.116.087-2.319 0 0 .733-.23 2.406.897a8.12 8.12 0 0 1 2.188-.295 8.12 8.12 0 0 1 2.187.295c1.674-1.137 2.407-.897 2.407-.897.48 1.203.175 2.1.087 2.32.558.612.897 1.388.897 2.35 0 3.358-2.045 4.102-3.992 4.32.317.274.59.8.59 1.62 0 1.17-.01 2.11-.01 2.406 0 .23.164.503.601.416A8.764 8.764 0 0 0 18.75 10 8.748 8.748 0 0 0 10 1.25Z"/></svg>
```

#### Adding a Storybook story to preview the file

Use [Storybook](https://storybook.js.org/) to preview the new logo.

Add a file called `social-logos.stories.tsx` to the `components/__design__` directory. If this file already exists, open it instead.

We want to create a file that looks like this, eventually, for this and the other logos (separate stories)

```tsx
import Image from 'next/image';
import type { Meta as MetaObj, StoryObj } from '@storybook/react';

export const SocialLogos: StoryObj = {};

export default {
  title: 'Design System/Logos',
  component: () => {
    return (
    <div>
      <div>
        <Image
            src="/static/images/logos/social-github.svg"
            alt="GitHub Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-mastadon.svg"
            alt="Mastadon Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-linkedin.svg"
            alt="LinkedIn Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-slack.svg"
            alt="Slack Logo"
            width={64}
            height={64}
          />
      </div>
      <div>
        <Image
            src="/static/images/logos/social-x.svg"
            alt="X Logo"
            width={64}
            height={64}
          />
      </div>
    </div>
  )},
} as MetaObj;
```

> Only add the `Image` for the logo you added.

#### Running Storybook

In a terminal, run `npm run storybook`.

Then, in a browser, go to http://localhost:6006/?path=/story/design-system-logos--social-logos and you should see the file you added.

#### Submitting the changes

[Submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) back to the main repository.

**Comment by dkanchanapalli** [comment]
Working on this issue.

**Comment by bmuenzenmeyer** [comment]
done
