### ISSUE TITLE
Add Tailwind and configure base tokens

### ISSUE THREAD

**Issue by bmuenzenmeyer** [bmuenzenmeyer/nodejs.org#9]
We’re going to adopt[ Tailwind ](https://tailwindcss.com/)CSS as a base design system. This will be useful for font-sizes, spacing, border-radius and pretty much crafting any component.

## Setup

Add tailwind as a dev dependency

```
npm install -D tailwindcss
```

Create a TypeScript file at the root of the project, `tailwind.config.ts`

```ts
import type { Config } from 'tailwindcss'

export default {
  content: [],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
```

## Color

[Color configuration](https://tailwindcss.com/docs/customizing-colors#using-custom-colors) should come from the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=469-11941&mode=design&t=or2YQ9xeYbw47kZf-4). 

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/f877edbf-31bf-45c8-90d3-ab51c889a35d)

In order we will have these base color families:
- Green
- Neutral
- Danger
- Warning
- Info
- Accent 1
- Accent 2
- White and Black

Each has 9 weights (100, 200, 300, 400, 500, 600, 700, 800, 900) inspectable within the Figma, and definable within Tailwind using the [additional colors config](https://tailwindcss.com/docs/customizing-colors#adding-additional-colors)

A future issue will create storybook stories for these colors. Do not do that as scope of this issue.  

## Text

[Customize the text configuration](https://tailwindcss.com/docs/font-size#customizing-your-theme) according to the [Figma design (direct link)](https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design&node-id=415-8257&mode=design&t=or2YQ9xeYbw47kZf-4). There are 11 sizes:

- xs
- sm
- base
- lg
- xl
- 2xl
- 3xl
- 4xl
- 5xl
- 6xl
- 7xl

Turn off 8xl and 9xl if possible. It is not in the design.

![image](https://github.com/bmuenzenmeyer/nodejs.org/assets/298435/96552777-aecf-41f5-ac18-820638118301)

[Configure the default font-family](https://tailwindcss.com/docs/font-family#customizing-your-theme) as Open Sans. It can be intergrated with Next using `next/font` using [their Tailwind documentation](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts#with-tailwind-css).

Update the [themeProvider](https://github.com/nodejs/nodejs.org/blob/main/providers/themeProvider.tsx) used by our Storybooks to inject the styles. (Either removing this body global style) and replace with a className surrounding children. This part may require iteration to get right.

A future issue will create storybook stories for these text sizes and styles. Do not do that as scope of this issue.

**Comment by bmuenzenmeyer** [comment]
I think I accounted for your comments. Spacing is all default TW, according to a comment from Hayden in the Figma

**Comment by ovflowd** [comment]
Nice one. The font one means that we need to replace how we currently inject the Next Font for the new style, as we've been doing via a `body` style tag, and I guess now we can do it as a variable with a `className`

It might be worth to add on the issue description the reference to where our current stuff is done.

As this will probably need to be updated https://github.com/nodejs/nodejs.org/blob/main/providers/themeProvider.tsx#L13. (Either removing this body global style) and replace with a className surrounding children. IDK

**Comment by bmuenzenmeyer** [comment]
@ovflowd ready for final review

**Comment by ovflowd** [comment]
> Update the [themeProvider](https://github.com/nodejs/nodejs.org/blob/main/providers/themeProvider.tsx?rgh-link-date=2023-08-12T04%3A15%3A43Z) used by our Storybooks to inject the stles. (Either removing this body global style) and replace with a className surrounding children. This part may require iteration to get right.

typo on stles

**Comment by bmuenzenmeyer** [comment]
cool. then i'll cut the issues to make storybooks once this is done... and we will have another chunk of work for the community to do while we write the meatier other work!
